services:
  backend:
    build: ./backend
    container_name: backend_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - dsa-network      
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  dsa-network:
    driver: bridge

volumes:
  mongodb_data: